[package]
name = "tiny-vector"
version = "0.1.0"
edition = "2021"

[dependencies]
indexmap = { version = "2.2.6", features = ["serde"] }
reqwest = { version = "0.12.5", features = ["json"] }
serde = { version = "1.0.203", features = ["derive"] }
tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
toml = { version = "0.8.14", features = ["preserve_order"] }
