[package]
name = "tiny-vector"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
tokio = { version = "1.38.0", features = [
    "macros",
    "rt-multi-thread",
    "sync",
    "time",
] }
